### ISSUE TITLE
UC38 : voltage mapping display (DrawVoltage Map)

### ISSUE THREAD

**Issue by drsewilliams** [openep/openep-py#1]
Plot a voltage map from the clinical data (representation – one function?) 

1. Anatomy – userdata.surface.triRep.X; userdata.surface.triRep.Triangulation 
2. Read voltage values - act_bip 
3. Colorbar - Colour palette scale the colorbar to the voltage value 
4. Shell - fix colour scale according to the logic in colorShell.m 
     - Fill threshold – 0.5mV 
     - interpolated shading of faces
     - drawing the free boundary
5. Voltage threshold

**Comment by jayrajan** [comment]
Comments by @drsewilliams 

Improvements:
1. The boundary itself should be drawn with a continuous line though rather than having gap
2. Face rendering; currently each face has a unique colour; while we should try to render using more of a continuous shading across the face like the matlab version

**Comment by jayrajan** [comment]
Further improvements:
- Directional Lighting with shadows.

**Comment by jayrajan** [comment]
DrawVoltage is now done using PyVista.
A drawMap abstract function has been created within openep.draw_routines.
The drawmap performs the rendering of the 3-d mesh using PyVista

**Comment by jayrajan** [comment]
Improvements to DrawMap():
- Return the parameters as Key-Value Parameters
- Include an input argument for plot = True/False, show plot+freeboundary lines when true else return p.
