### ISSUE TITLE
Linking 3D viewers

### ISSUE THREAD

**Issue by drsewilliams** [openep/openep-py#90]
See issue #88 for a description of 3D viewer

If multiple 3D viewers are open, there should be an option to 'link' the view so that if one is rotated/pan, the other(s) rotate/pan etc.

**Comment by p-j-smith** [comment]
It's not currently possible to do this in pyvista, but I've opened a PR with pyvistaqt to add the ability to link views across different plotters: https://github.com/pyvista/pyvistaqt/pull/133

**Comment by drsewilliams** [comment]
Hi Paul, I reviewed the PR on pyvista - looks like great work. If pyvista accept the PR that's great, but if they don't can we still provide this functionality in OpenEP-py?

**Comment by p-j-smith** [comment]
Yeah we can do, we could subclass their `BackgroundPlotter` and add the functionality to our own plotter class. But adding to pyvistaqt would be preferable for various reasons - including that it is fairly widely used and so issues with the implementation are more likely to found by other users sooner. Plus it's nice to give a little something back to these really useful packages we're building openep-py on top of.
