### ISSUE TITLE
GUI terminates when selecting electrograms to view

### ISSUE THREAD

**Issue by drsewilliams** [openep/openep-py#91]
Description of issue:

1. Loaded case 'new_dataset_2.mat'
2. Clicked on EGM panel
3. entered the text '4 8' in the box to the right of 'Select EGMs'
4. clicked on 'Select EGMs (indices of points)
5. Application terminated

Console output:

```
(base) c108206:~ Steven$ openep
QLayout: Attempting to add QLayout "" to OpenEpGUI "", which already has a layout
qt.qpa.window: <QNSWindow: 0x7fd159833b20; contentView=<QNSView: 0x7fd157f902f0; QCocoaWindow(0x7fd157f83640, window=QWidgetWindow(0x7fd157f81950, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
QLayout: Attempting to add QLayout "" to OpenEpGUI "", which already has a layout
qt.qpa.window: <QNSWindow: 0x7fd159846ee0; contentView=<QNSView: 0x7fd159a07f10; QCocoaWindow(0x7fd159a04770, window=QWidgetWindow(0x7fd154ff7240, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
QLayout: Attempting to add QLayout "" to OpenEpGUI "", which already has a layout
Traceback (most recent call last):
  File "/Users/Steven/Documents/openep-py/openep/view/view_gui.py", line 582, in update_electrograms
    self.egm_points = np.asarray(self.egm_select.text().split(','), dtype=int)
ValueError: invalid literal for int() with base 10: '4 8'
Abort trap: 6
```

**Comment by p-j-smith** [comment]
Thanks for raising this. This happens because of the fragile way the input is handled at the minute. 'Select EGMs' expects the indices to be comma-separated, e.g. '4, 8'.

This will no longer be a problem when #93 is implemented, but in the meantime it might be worth accepting whitespace-separated text too.

**Comment by drsewilliams** [comment]
Thanks, 

I think we may wish to also have text input in addition to UI input like #93. For example, I can imagine a situation in which we have an [OpenEP Workflow](https://zenodo.org/communities/openepworkflows/?page=1&size=20) which requires analysis of a certain set of points, or outputs a certain set of points. Having the option to 'copy-and-paste' this into the UI could therefore be useful.

So, if possible I would suggest accepting commas _or_ whitespace as the separates.
