### ISSUE TITLE
Update GUI to be usable when Dark Mode is enabled on MacOS

### ISSUE THREAD

**Issue by drsewilliams** [openep/openep-py#94]
When Dark Mode is enabled on MacOS some of the colours of UI elements change, where as some do not. For example, text becomes unreadable.

![image](https://user-images.githubusercontent.com/30099842/141957849-52df4a8f-093f-4cd4-8b30-f80b3ca8f705.png)

**Comment by p-j-smith** [comment]
The appearance of the GUI should be now be independent of whether dark mode is on or off. At some point we could look into adding separate styles for light/dark mode.

**Comment by drsewilliams** [comment]
Great, I'll take a look. I think it is fine that the GUI does not reflect light/dark modes for now - happy to close this issue.
